# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec9deac868ff1bd01301e279494e4193704dc30ed496a6837bf7c1c962ebab12c08e71c22e61c9845846a7af6169c95498085f456843f1efeeaead50e09ce65c

test:
  secret_key_base: 6682431fa813097b56dc90a54a90f21a44b479bbd9ba8c24af475b100cd71d824e71cd0d873822e54afe281ff6cc202e5f333fe97bc37c6f0c19c9c036ec2a82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
